#!/data/data/com.termux/files/usr/bin/bash -e

cd $HOME
###
neofetch --ascii_distro Kali -L
###
axel -a --search -o kali-full.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz
###
cat << EOF
[*] Extracting rootfs...!!!
[*] 20 minutes to extract please wait...!!!
EOF
###
proot --link2symlink bsdtar -xpJf kali-full.tar.xz 2>/dev/null
###
cat >>$PREFIX/etc/bash.bashrc << EOF
clear
neofetch --ascii_distro Kali -L
(kali vnc) &
kali
EOF
###
wget -O kali-arm64/bin/vnc https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/vnc
###
chmod 700 kali-arm64/bin/vnc
###
wget -O $PREFIX/bin/nethunter https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/nethunter
###
chmod 700 $PREFIX/bin/nethunter
###
ln -s $PREFIX/bin/nethunter $PREFIX/bin/kali
###
sed -i '/if/,/fi/d' kali-arm64/root/.bash_profile
###
echo "nameserver 9.9.9.9" > kali-arm64/etc/resolv.conf
###
echo "nameserver 8.8.4.4" >> kali-arm64/etc/resolv.conf
###
wget -O kali-arm64/root/.bashrc https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/rcfiles/rootbash.bashrc
###
wget -O kali-arm64/home/kali/.bashrc https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/rcfiles/homebash.bashrc
###
wget -O kali-arm64/etc/bash.bashrc https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/rcfiles/etcbash.bashrc
###
echo "export PULSE_SERVER=127.0.0.1" >> kali-arm64/home/kali/.vnc/xstartup
###
chmod +s kali-arm64/usr/bin/sudo
###
chmod +s kali-arm64/usr/bin/su
###
echo "kali    ALL=(ALL:ALL) ALL" > kali-arm64/etc/sudoers.d/kali
###
echo "Set disable_coredump false" > kali-arm64/etc/sudo.conf
###
cat << EOF
[*] Type: kali vnc passwd
[*] Type: kali vnc &
EOF
###
USRID=$(id -u)
###
GRPID=$(id -g)
###
kali -r usermod -u "$USRID" kali 2>/dev/null
###
kali -r groupmod -g "$GRPID" kali 2>/dev/null
