#!/data/data/com.termux/files/usr/bin/bash

# Install required packages
apt install proot bsdtar axel neofetch -y
clear

cd ${HOME}

### Set variables
TAR="kali-nethunter-rootfs-full-arm64.tar.xz"
DIR="kali-arm64"
NM="kali"

# Display system info
neofetch --ascii_distro Kali -L

# Download Kali rootfs
axel -a -o ${TAR} https://kali.download/nethunter-images/current/rootfs/${TAR}

# Create a proot-distro configuration file
cat << EOF
Checking file integrity of ${TAR}...
EOF
cat > $HOME/${TAR}_SHA256 << EOF
${TAR}_SHA512=>$(sha512sum ${TAR} | awk '{print $1}')
EOF
echo " "
cat $HOME/${TAR}_SHA256

# Extract rootfs
echo " "
echo "[*] Decompressing 14GB of files takes 15 minutes..."
sleep 1s
echo "[*] Please wait..."
sleep 1s
echo "[*] Extracting ${TAR}..."
proot --link2symlink bsdtar -xpJf ${TAR} 2>/dev/null

# Update bash.bashrc
cat >> $PREFIX/etc/bash.bashrc << EOF
(${NM} vnc) &
${NM}
EOF

# Download and configure scripts
wget -O ${DIR}/usr/bin/vnc https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/vnc
termux-fix-shebang ${DIR}/usr/bin/vnc
chmod 755 ${DIR}/usr/bin/vnc

# Adding shortcut file
wget -O $PREFIX/bin/${NM} https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/kali
termux-fix-shebang $PREFIX/bin/${NM}
chmod 755 $PREFIX/bin/${NM}

# Add neofetch
wget -O ${DIR}/bin/neofetch https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/neofetch
chmod 755 ${DIR}/bin/neofetch

# Add uninstallation config file
cat > $PREFIX/bin/${NM}-uninstall << EOF
rm -rf $HOME/${DIR}
rm -rf $PREFIX/bin/${NM}
rm -rf ${DIR}/bin/vnc
sed -i 's/(${NM} vnc) &//g' $PREFIX/etc/bash.bashrc
sed -i 's/${NM}//g' $PREFIX/etc/bash.bashrc
rm -rf $PREFIX/bin/${NM}-uninstall
EOF
chmod 700 $PREFIX/bin/${NM}-uninstall

# Download configuration files
wget -O ${DIR}/home/${NM}/.bashrc https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/rcfiles/home.bashrc

# Modify .bash_profile
sed -i '/if/,/fi/d' ${DIR}/root/.bash_profile

# Set SUID for sudo and su
chmod +s ${DIR}/usr/bin/sudo
chmod +s ${DIR}/usr/bin/su

# Fix DNS issue
cat > ${DIR}/etc/resolv.conf << EOF
nameserver 9.9.9.9
nameserver 8.8.8.8
nameserver 1.1.1.1
EOF

# Fix sudoer
cat > ${DIR}/etc/sudoers.d/${NM}
${NM}    ALL=(ALL:ALL) ALL
EOF

# Update bash.bashrc inside chroot
cat >> ${DIR}/etc/bash.bashrc << EOF
neofetch
EOF

# Configure sudo.conf
cat > ${DIR}/etc/sudo.conf << EOF
Set disable_coredump false
EOF

# Modify user and group IDs
USRID=$(id -u)
GRPID=$(id -g)
${NM} -r usermod -u $USRID ${NM} 2>/dev/null
${NM} -r groupmod -g $GRPID ${NM} 2>/dev/null

# Delete tarball
rm ${TAR}

# Start chroot environment
bash ${NM} -r

# Update and install neofetch
sudo apt update
sudo apt install neofetch -y

# Display success message
echo -e '\e[1;93m'
cat << EOF
[*] To configure VNC password
[*] Type: kali vnc passwd
[*] Type: kali vnc &
EOF
