#!/data/data/com.termux/files/usr/bin/bash

# Install required packages
apt install proot bsdtar libxml2 axel neofetch -y
clear

cd $HOME

# Set variables
TAR=kali-minimal-arm64.tar.xz
DIR=kali-arm64
NM=kali

# Display system info
neofetch --ascii_distro Kali

# Download Kali rootfs
axel -o $TAR https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-minimal-arm64.tar.xz

# Check file integrity
echo " "
echo "[*] Checking $NM Linux File Integrity...!!!"
echo " "
echo "[*] MD5"
md5sum $TAR
echo " "
echo "[*] SHA256"
sha256sum $TAR
echo " "
echo "[*] SHA512"
sha512sum $TAR

# Extract rootfs
echo " "
echo "[*] Extracting $TAR, Please wait...!!!"
proot --link2symlink bsdtar -xpJf $TAR 2>/dev/null

# Update bash.bashrc
cat >> $PREFIX/etc/bash.bashrc << EOF
clear
$NM
EOF

# Adding shortcut file
cat > "$PREFIX/bin/$NM" <<- EOF
#!/data/data/com.termux/files/usr/bin/bash -e
cd \${HOME}
## termux-exec sets LD_PRELOAD so let's unset it before continuing
unset LD_PRELOAD
## Workaround for Libreoffice, also needs to bind a fake /proc/version
if [ ! -f $DIR/root/.version ]; then
    touch $DIR/root/.version
fi

## Default user is "kali"
user="$NM"
home="/home/\$user"
start="sudo -u kali /bin/bash"

## NH can be launched as root with the "-r" cmd attribute
## Also check if user kali exists, if not start as root
if grep -q "kali" ${DIR}/etc/passwd; then
    KALIUSR="1";
else
    KALIUSR="0";
fi
if [[ \$KALIUSR == "0" || ("\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R")) ]];then
    user="root"
    home="/\$user"
    start="/bin/bash --login"
    if [[ "\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R") ]];then
        shift
    fi
fi

cmdline="proot \\
        --link2symlink \\
        -0 \\
        -r $DIR \\
        -b /dev \\
        -b /proc \\
        -b /sdcard \\
        -b $DIR\$home:/dev/shm \\
        -w \$home \\
           /usr/bin/env -i \\
           HOME=\$home \\
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \\
           TERM=\$TERM \\
           LANG=C.UTF-8 \\
           \$start"

cmd="\$@"
if [ "\$#" == "0" ];then
    exec \$cmdline
else
    \$cmdline -c "\$cmd"
fi
EOF
chmod 700 $PREFIX/bin/$NM

# Add neofetch
wget -O $DIR/bin/neofetch https://raw.githubusercontent.com/xiv3r/Kali-Linux-Termux/refs/heads/main/kali_nethunter/neofetch
chmod 700 $DIR/bin/neofetch

# Add uninstallation config file
cat > $PREFIX/bin/$NM-uninstall << EOF
rm -rf $HOME/$DIR
rm -rf $PREFIX/bin/$NM
sed -i 's/clear//g' $PREFIX/etc/bash.bashrc
sed -i 's/$NM//g' $PREFIX/etc/bash.bashrc
rm -rf $PREFIX/bin/$NM-uninstall
EOF
chmod 700 $PREFIX/bin/$NM-uninstall

# Modify .bash_profile
sed -i '/if/,/fi/d' $DIR/root/.bash_profile

# Set SUID for sudo and su
chmod +s $DIR/usr/bin/sudo
chmod +s $DIR/usr/bin/su

# Fix DNS issue
cat > $DIR/etc/resolv.conf << EOF
nameserver 9.9.9.10
EOF

# Fix sudoer file
cat > $DIR/etc/sudoers.d/$NM << EOF
$NM    ALL=(ALL:ALL) ALL
EOF

# Update bash.bashrc inside chroot
cat >> $DIR/etc/bash.bashrc << EOF
neofetch
EOF

# Configure sudo.conf
cat > $DIR/etc/sudo.conf << EOF
Set disable_coredump false
EOF

# Modify user and group IDs
USRID=$(id -u)
GRPID=$(id -g)
$NM -r usermod -u $USRID $NM 2>/dev/null
$NM -r groupmod -g $GRPID $NM 2>/dev/null

# Delete tarball
rm $TAR

# Display success message
cat << EOF
[*] Successful Installation...!

[*] To Login Kali Nethunter Minimal Type: $NM
EOF
